_commit: v0.4.63
_src_path: git@github.com:tschm/experiments.git
description: Client for the cvxball server
gh_create: gh repo create tschm/cvxball-client --public --description 'Client for
  the cvxball server'
page: https://tschm.github.io/cvxball-client
project_name: cvxball-client
repository: https://github.com/tschm/cvxball-client
ssh_uri: git@github.com:tschm/cvxball-client.git
status: public
username: tschm
